### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by YannSuissa** [NoahZinsmeister/web3-react#51]
**Bug Description**

Hi, I wan't to try and use the library, and of course the last version.

I'm under Windows here are the command i used :

> git clone https://github.com/NoahZinsmeister/web3-react.git
> yarn
> yarn bootstrap
> yarn build

```
yarn run v1.19.1
$ lerna run build
lerna notice cli v3.18.4
lerna info Executing command in 15 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@web3-react/types' in 8.2s:
$ tsdx build
✓ Creating entry file 4.2 secs
✓ Building modules 1.5 secs
lerna ERR! yarn run build exited 1 in '@web3-react/abstract-connector'
lerna ERR! yarn run build stdout:
$ tsdx build
✓ Creating entry file 4.9 secs
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
(typescript) Error: C:/_CODE/react/web3-react/packages/abstract-connector/src/index.ts(7,8): semantic error TS2307: Cannot find module '@web3-react/types'.
Error: C:/_CODE/react/web3-react/packages/abstract-connector/src/index.ts(7,8): semantic error TS2307: Cannot find module '@web3-react/types'.
    at error (C:\_CODE\react\web3-react\node_modules\rollup\dist\rollup.js:5351:30)
    at throwPluginError (C:\_CODE\react\web3-react\node_modules\rollup\dist\rollup.js:11668:12)
    at Object.error (C:\_CODE\react\web3-react\node_modules\rollup\dist\rollup.js:12637:24)
    at Object.error (C:\_CODE\react\web3-react\node_modules\rollup\dist\rollup.js:11867:38)
    at RollupContext.error (C:\_CODE\react\web3-react\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:17194:30)
    at lodash_3 (C:\_CODE\react\web3-react\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:24958:23)
    at arrayEach (C:\_CODE\react\web3-react\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:534:11)
    at forEach (C:\_CODE\react\web3-react\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:9360:14)
    at printDiagnostics (C:\_CODE\react\web3-react\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:24931:5)
    at Object.transform (C:\_CODE\react\web3-react\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:27373:17)
error Command failed with exit code 1.**

```

I also have another react beginner question, i've already have started a project how will i integrate the lib? should i just use the directory with and import? of is there a better practice?

Thanks in advance for helping !

Yann

**Comment by NoahZinsmeister** [comment]
Hmm this is a new one @YannSuissa . Can you report your `yarn --version` and `node --version`? It's also possible it's a Windows thing...

To your other question, you don't actually have to build the library locally to use it! The easiest way is just to `yarn add @web3-react/<blah>` to your project! [See the demo](https://codesandbox.io/s/web3-react-v6-8rg3h?fontsize=14&hidenavigation=1&theme=dark).

**Comment by YannSuissa** [comment]
Hi @NoahZinsmeister , 

Thanks for your response : 
```
$ yarn --version
1.19.1
$ node --version
v10.15.3
```

When i used the `npm i web3-react` it's the v5, i wanted to use the v6, that's why I ended here.
About `yarn add @web3-react/<blah>`, i've never really used yarn, and mixing npm and yarn is a good idea in terms of lock files i guess.

Anyway i started with the v5 now since on your github you publish an example for the v5 (on the top) and another for the v6. (the quickstart button)

Thanks!

**Comment by NoahZinsmeister** [comment]
ok no problem! going to mark this as resolved, let me know if you have any more questions and i'm happy to reopen.
