### ISSUE TITLE
Yarn install sub-dependencies issue

### ISSUE THREAD

**Issue by daihovey** [NoahZinsmeister/web3-react#54]
**Bug Description**
Cannot install sub-dependencies

**Reproduction**
When installing sub-dependencies, I see these errors:

```
MacBook-Pro:web3-react dai$ yarn bootstrap
yarn run v1.19.2
$ lerna bootstrap
lerna notice cli v3.19.0
lerna info Bootstrapping 15 packages
lerna info Installing external dependencies
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in '@web3-react/ledger-connector'
lerna ERR! yarn install --mutex network:42424 --non-interactive stdout:
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

lerna ERR! yarn install --mutex network:42424 --non-interactive stderr:
warning Waiting for the other yarn instance to finish (92382)
warning Waiting for the other yarn instance to finish (92374)
error /dai/web3-react/packages/ledger-connector/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /dai/web3-react/packages/ledger-connector/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@13.2.0 | darwin | x64
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/13.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/dai/web3-react/packages/ledger-connector/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/13.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/dai/Library/Caches/node-gyp/13.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/dai/Library/Caches/node-gyp/13.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/13.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/dai/Library/Caches/node-gyp/13.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/dai/web3-react/packages/ledger-connector/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/sha3/src/addon.o
In file included from ../src/addon.cpp:9:
In file included from ../src/KeccakNISTInterface.h:17:
../src/KeccakSponge.h:23:9: warning: 'ALIGN' macro redefined [-Wmacro-redefined]
#define ALIGN __attribute__ ((aligned(32)))
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/i386/param.h:83:9: note: previous definition is here
#define ALIGN(p)        __DARWIN_ALIGN(p)
        ^
../src/addon.cpp:83:11: error: no matching member function for call to 'Set'
                target->Set(className, f);
                ~~~~~~~~^~~
/dai/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/dai/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
1 warning and 1 error generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/13.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/13.2.0/bin/node" "/usr/local/Cellar/node/13.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /dai/web3-react/packages/ledger-connector/node_modules/sha3
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
Process stalled
Active handles:
  - Socket
  - Socket
  - Socket
  - Socket
  - Socket
  - ChildProcess
  - Socket
  - Socket
  - ChildProcess
  - Socket
  - Socket
  - ChildProcess
  - Socket
  - Socket
  - ChildProcess

lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in '@web3-react/ledger-connector'
lerna WARN complete Waiting for 7 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`yarn version: 1.19.2`
`node version: v13.2.0`
`macOS : 10.14.6`

**Steps to reproduce:**
`git clone https://github.com/NoahZinsmeister/web3-react.git`
`yarn`
`yarn bootstrap`

**Expected Behavior**
Sub-dependencies install without error

**Additional Context**

**Comment by daihovey** [comment]
Also unsure if related but also seeing this error when running (`yarn start`) the example:

```MacBook-Pro:example dai$ yarn start
yarn run v1.19.2
$ parcel index.html
Server running at http://localhost:1234 
🚨  /dai/web3-react/packages/core/dist/index.js:7:27: Cannot resolve dependency './core.cjs.development.js' at '/dai/web3-react/packages/core/dist/core.cjs.development.js'
  5 |   module.exports = require('./core.cjs.production.min.js')
  6 | } else {
> 7 |   module.exports = require('./core.cjs.development.js')```

**Comment by NoahZinsmeister** [comment]
@daihovey hmm, can you try the install with node@10, or if that doesn't work, node@12? those are the two versions we CI against (https://github.com/NoahZinsmeister/web3-react/runs/337760758)

**Comment by NoahZinsmeister** [comment]
that error you're getting in `example/` is almost certainly related to something about your `yarn`/`yarn bootstrap`/`yarn build`/`yarn start` process in the root being messed up. though note that i've also some had weird issues with parcel occasionally, so once we iron out the install issue let's definitely make sure that the example works!

**Comment by daihovey** [comment]
Yeh thought it might be node version issues. 
The second issue I fixed by removing the `"alias"`'s from the `package.json` and `yarn add`ing them myself 
P.s. thanks for the great library 📿
